
defaults:
  resources:
    instance-type: C4 # C5, P4000, etc., will also work
  env:
    PAPERSPACE_API_KEY: secret:my-key

jobs:

  # 1. Clone recommender repo

  # The repo is public so no GitHub authorization credentials are required
  # The URL has to be without .git extension
  # The checkout results in an output volume that is then referred to in subsequent jobs in this file

  CloneRecRepo:
    outputs:
      repoRec:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/yunnne/Deep-Learning-Recommender-TF/

  # 2. Train model

  # The job calls the Python script workflow_train_model.py
  # Model hyperparameters are passed in as environment variables using the env keyword
  # The script outputs the saved model to /outputs/trainedRecommender, a versioned Gradient Dataset

  RecommenderTrain:
    needs:
      - CloneRecRepo
    inputs:
      repoRec: CloneRecRepo.outputs.repoRec
    env:
      HP_FINAL_EPOCHS: '50'
      HP_FINAL_LR: '0.1'
    outputs:
      trainedRecommender:
        type: dataset
        with:
          ref: recommender
    uses: script@v1
    with:
      script: |-
        cp -R /inputs/repoRec /Deep-Learning-Recommender-TF
        cd /Deep-Learning-Recommender-TF
        python workflow_train_model.py
      image: tensorflow/tensorflow:3.9.1-jupyter
